### ISSUE TITLE
OSX - Watching 3 or more directories fails

### ISSUE THREAD

**Issue by compressed** [passcod/rsnotify#23]
Hi,
I'm running OSX 10.10.4 and was trying to use the cargo watch tool, however it wasn't working. It seemed whenever the "benches" watch was added, cargo watch wouldn't watch anything...

Digging further, it seems something goes awry when adding the third watch. For the prior two watches, this condition is met (`fsevent.rs` line 62):

```rust
    if !self.is_running() {
      return;
    }
```
On the third try however, that condition isn't met, and it makes its way all the way to this match (`fsevent.rs` line 78):

```rust
      match context_info.done.recv() {
        Ok(()) => (),
        Err(_) => panic!("the runloop may not be finished!"),
      }
```
And never makes it past there...

Let me know if you need more information.

Also, if I try running cargo test, it fails:

```
~/rsnotify git:master ❯❯❯ cargo test                                                                                                                                                                                            ⏎
     Running target/debug/notify-a00f19333567126a

running 1 test
test fsevent::test_fsevent_watcher_drop ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured

     Running target/debug/notify-b65501780e7463a9

running 7 tests
test new_null ... ok
test new_fsevent ... ok
test new_recommended ... ok
test new_poll ... ok
test watch_dir_recommended ... FAILED
test watch_single_file_poll ... ok
test watch_single_file_recommended ... FAILED

failures:

---- watch_dir_recommended stdout ----
	thread 'watch_dir_recommended' panicked at 'assertion failed: `(left == right)` (left: `"/private/var/folders/b5/yh22bw792yj4n0q68vckrbjw0000gn/T/dir.KTsLmVgBAqyo"`, right: `"/var/folders/b5/yh22bw792yj4n0q68vckrbjw0000gn/T/dir.KTsLmVgBAqyo/dir1.W4y90yVhB8oP/dir11.EPrh1Cq6JFaE/.9ZIU5fW5tHKo"`)', tests/notify.rs:16


---- watch_single_file_recommended stdout ----
	thread 'watch_single_file_recommended' panicked at 'assertion failed: `(left == right)` (left: `"/private/var/folders/b5/yh22bw792yj4n0q68vckrbjw0000gn/T/.D36zoPQgBQr0"`, right: `"/var/folders/b5/yh22bw792yj4n0q68vckrbjw0000gn/T/.D36zoPQgBQr0"`)', tests/notify.rs:16



failures:
    watch_dir_recommended
    watch_single_file_recommended

test result: FAILED. 5 passed; 2 failed; 0 ignored; 0 measured

thread '<main>' panicked at 'Some tests failed', /Users/rustbuild/src/rust-buildbot/slave/stable-dist-rustc-mac/build/src/libtest/lib.rs:255
```

**Comment by passcod** [comment]
Any ideas, @octplane?

**Comment by jakerr** [comment]
The test failure seems to be because fsevent-rust resolves symlinks here in [cf::str_path_to_cfstring_ref](https://github.com/octplane/fsevent-rust/blob/master/fsevent-sys/core_foundation.rs#L156). Then the test asserts it got an event on `/var/folders...` but its event is on `/var/private/folders...` this is due to the fact that `/var` is a symlink to `/private/var` on OS X

I'm not sure if the resolution of symlinks at that place is expected or not. If it is then the tests can be fixed by resolving the symlink before asserting.

**Comment by jakerr** [comment]
Oops my comment may be a bit misleading. While it is *an* issue it's not *the* issue as you can see the directory events expected in `watch_dir_recommended` are even out of order.

**Comment by passcod** [comment]
There's an issue open for symlinks iirc. On my phone, can't check.

**Comment by octplane** [comment]
Oops, didn't receive any notification about this bug until yesterday. Sorry for the delay, I'll look into it quickly...

**Comment by octplane** [comment]
The runloop stuff is a bit curious. I have made my binding testable and I does not fail with three folder to listen. It does none of the stop/start of rsnotify https://github.com/passcod/rsnotify/blob/master/src/fsevent.rs#L223 (which I'm not sure it the right way to do)

However, the FSEvent API resolves all symlinks when calling back its listener and I suppose this behavior is not compatible with the other bindings.

Also, some events sent by the FSEvent API are from the 'past' (this is another very troublesome issue that might or might not be due the API itself...).

All these difficulties will make testing this not cool :) But I'm on it :D

**Comment by passcod** [comment]
@compressed, etc Does this still occur?

**Comment by passcod** [comment]
Closing. Comment/reopen if it's still occurring.
