### ISSUE TITLE
Additional maintainers + Vision

### ISSUE THREAD

**Issue by passcod** [passcod/rsnotify#24]
I'm going on a 5-week holiday soon, and will probably not be available to do much on this during that time. Even apart from that, I'm generally quite busy from work and my contributions to Notify have been reduced to merging changes and shaping discussions for a little while now.

I'm looking for maintainers to help with this. You'll get commit and crates.io access, a nice badge on your posts in issue threads, and eternal thanks.

My vision for Notify can be summarised thus:
- A single library for file watching in Rust, à la `fs.watch` in node, `Listen` in Ruby, `fsnotify` in Go.
- I'd love for it to be embeddable / usable in other languages. C is the obvious target here, but there has been some recent forays in Python-to-Rust-and-back, for example.
- Since #22, Notify should be able to watch both directories and single files.
- A single interface for file watching. Yes, different system interfaces have different options, and one may want to take advantage of some advanced feature of one, but not here. They can use a binding directly. Notify should remain the same across all platforms and implementations.
- Abstract away as much as possible from the backends. See [this comment on #22](https://github.com/passcod/rsnotify/pull/22#issuecomment-120675182). Afaik, `fanotify` on Linux is the only backend that could provide recursive directory watches natively. Notify should allow `fanotify` to handle that, as it will do so far more efficiently than us, but it should also take care of recursive watching for the other backends.
- A more advanced vision of the above is to compose backends if necessary. On Windows, the native call can only watch directories, not files. We could implement single file watching by watching the directory above and filtering events, or we could use the PollWatcher to watch that file. The behaviour could be chosen dynamically, e.g. a large amount of sibling files in that directory may generate a large amount of events, and in that case it would be preferable to switch to a PollWatcher.
- Speaking of, the current PollWatcher is lacking terribly, see #20.

Pinging those of the current contributors who aren't watching this repo: @blaenk @octplane @andelf @retep998 and I'll also [post this on Reddit](https://www.reddit.com/r/rust/comments/3em15p/looking_for_additional_maintainers_for_notify/) for visibility.

**Comment by passcod** [comment]
Note that my vision has been malleable in the past... these are not rules to follow:

![More like guidelines](http://cdn.meme.am/instances/500x/57097238.jpg)

**Comment by nagisa** [comment]
I always had a similar project (and my own ideas about it) in mind, so if there’s nobody who steps up, I could.

**Comment by Polyg0n** [comment]
I could definitely pitch in! 
I'm going back to college 3rd of next month, but! That doesn't mean I can't pitch in now and even after I go back!

**Comment by retep998** [comment]
I guess I can maintain the Windows specific code. Maybe I should stop waiting for @maurizi and just finish my implementation and submit it.

**Comment by Polyg0n** [comment]
I'm on a Macbook so I could maintain and patch up OS-X/Linux distro code.

**Comment by blaenk** [comment]
I'll help out. And yeah, we're still sorely lacking a windows driver.

**Comment by passcod** [comment]
Awesome :) I'll add @blaenk and @retep998 for now.

**Comment by franleplant** [comment]
My two cents:

I'd like to make myself available as a _junior_ maintainer if something as such exists.

I have access to Linux, Mac and Windows machines and I consider myself a Rust beginner, perhaps I could make myself useful in common tasks, improving the docs and so on and so for. Just let me know.
My goal is to learn and contribute.

Thanks!
Fran

**Comment by Polyg0n** [comment]
I'm with @franleplant, I just started learning Rust like 2 weeks ago.

**Comment by passcod** [comment]
@franleplant @Polyg0n The best thing to do in this case is to submit pull requests and participate in issues if you feel like you can be helpful :) Documentation and tests would be great contributions to start easily.

**Comment by franleplant** [comment]
@passcod great, thank you very much!

**Comment by Polyg0n** [comment]
@passcod Not a problem! Can do :smile:
