### ISSUE TITLE
4 events on file change

### ISSUE THREAD

**Issue by azerupi** [passcod/rsnotify#30]
I get 4 times the same event on a file change.

```
Event: Event { path: Some("/home/azerupi/Programming/Rust/mdBook/book-example/src/SUMMARY.md"), op: Ok(WRITE) }
File changed: "/home/azerupi/Programming/Rust/mdBook/book-example/src/SUMMARY.md"

Event: Event { path: Some("/home/azerupi/Programming/Rust/mdBook/book-example/src/SUMMARY.md"), op: Ok(WRITE) }
File changed: "/home/azerupi/Programming/Rust/mdBook/book-example/src/SUMMARY.md"

Event: Event { path: Some("/home/azerupi/Programming/Rust/mdBook/book-example/src/SUMMARY.md"), op: Ok(WRITE) }
File changed: "/home/azerupi/Programming/Rust/mdBook/book-example/src/SUMMARY.md"

Event: Event { path: Some("/home/azerupi/Programming/Rust/mdBook/book-example/src/SUMMARY.md"), op: Ok(WRITE) }
File changed: "/home/azerupi/Programming/Rust/mdBook/book-example/src/SUMMARY.md"
```

I am on Arch Linux, using v2.3.2 of notify

**EDIT:** At the moment, the workaround i found was to return and call the watching function recursively

```rust
fn watch(args: &ArgMatches) -> Result<(), Box<Error>> {
    // Create a channel to receive the events.
     let (tx, rx) = channel();
     let w: Result<notify::RecommendedWatcher, notify::Error> = notify::Watcher::new(tx);

     match w {
         Ok(mut watcher) => {
             watcher.watch("path").unwrap();

             loop {
                 match rx.recv() {
                     Ok(event) => {
                         if let Some(path) = event.path {
                             println!("File changed: {:?}\n", path);
                             // Do things...
                             // Hack to prevent receiving the event 4 times
                             return watch(args); // <---------------------------------
                         } else {
                             continue;
                         }
                     },
                     Err(e) => { println!("An error occured: {:?}", e); }
                 }
             }
         },
         Err(e) => { ::std::process::exit(0); }
     }
    Ok(())
}
```

**Comment by passcod** [comment]
What are you using to change the file? Does a simple `touch` trigger this, or is this a program (which may have its own weird behaviour)?

**Comment by azerupi** [comment]
Thanks for the fast reply! :)

I was using Atom to change the files, just modifying and saving. I will try with touch and let you know if that changed anything.

**Comment by blaenk** [comment]
Yeah, oftentimes editors and programs have their own ways of saving/writing files, like they might save to a separate file and then rename it to the target file. For example, vim and emacs don't simply just write to the file directly from what I've observed. You'll notice touch by itself does do what you expect. You'll have to accommodate the way atom does it yourself.

**Comment by azerupi** [comment]
Ah ok, thanks for the clarification!
In that case I will close the issue and keep my workaround :)
Thanks!

**Comment by blaenk** [comment]
No need to close it if what I said ended up not applying to your situation, since I can't be sure. It does seem weird that atom is creating that many write events, but then I'm not sure how atom works. One thing you can do to check though is like @passcod said, try using `touch` on the file and you should see what you expect, a single event. That will rule out your code being the problem; I doubt your code is the problem.

Honestly recursing like you are in your workaround doesn't seem very sound. I think it's creating separate "inotify instances" so basically you get one event, you process it, then you create another inotify instance which means you start with a fresh "event queue" which is why you don't "get" the repeated events. I think a better approach would avoid recreating inotify instances (i.e. `notify::Watcher::new`) and instead introduce perhaps some sort of debouncing logic to ignore repeated events within a certain short timespan, or something.

**Comment by azerupi** [comment]
I will just re-open if there is indeed a bug.

> Honestly recursing like you are in your workaround doesn't seem very sound.

I know, what I am most afraid of is to hit the max recursion limit.. I should probably try to find a more clever solution like you said. 

> instead introduce perhaps some sort of debouncing logic to ignore repeated events within a certain short timespan

I agree, this would be a more robust solution. I am not sure however this would be trivial to implement in my case, because the action I do after a file changed takes a little time (± 1s). And as I understand it, the events are queued in the receiver until processed. So the time I would measure would not be the time between the events but the time it took the action to complete...
I tried to find a way to empty the receiver `rx`, to clear all the events that happened while doing the task, but I didn't find any method for that in the std docs. Seems kind of weird that you can't flush it. 

Do you have a solution?

**Comment by passcod** [comment]
Maybe just `recv` the events and then immediately discard them if you're processing the action? I do something similar in cargo-watch (which was the original reason for notify to exist).
