### ISSUE TITLE
consider using walkdir crate

### ISSUE THREAD

**Issue by blaenk** [passcod/rsnotify#31]
We might want to switch over to @BurntSushi's [walkdir](https://github.com/BurntSushi/walkdir) crate which may end up being more popular and therefore (hopefully) better maintained than the one @passcod extracted into walker.

We can evaluate this further after some time to see how things pan out, but the stuff from @BurntSushi is solid.

**Comment by passcod** [comment]
:+1:

**Comment by blaenk** [comment]
Forgot to mention this but I hope it was implied. walkdir is working great for us now; there isn't much more we need at the moment. This is meant with an eye towards future maintainability.

**Comment by BurntSushi** [comment]
Is it the same implementation that it's `std`? If so, I imagine you'll run into this issue at some point soon: https://github.com/rust-lang/rust/issues/23715

**Comment by passcod** [comment]
Walker is a straight rip-out of what was (is?) in unstable std at 1.0. Perhaps a couple of lines were changed. So yes, we probably hit this issue.

**Comment by passcod** [comment]
Tbh the fd limit is probably higher than the inotify watch limit by default, so it's possible we don't see it by virtue of hitting the other limit first.

**Comment by passcod** [comment]
Shipped in v2.5.2.
