### ISSUE TITLE
windows appveyor build failing

### ISSUE THREAD

**Issue by jmquigs** [passcod/rsnotify#43]
Affects #40 but will also affect master when the next build is done.  I thought this was due to the fact that appveyor had updated to VS2015 Update 1, but I did the same update on my system and don't see the problem.
`note: LINK : fatal error LNK1181: cannot open input file 'ws2_32.lib'`

full log:
https://ci.appveyor.com/project/passcod/rsnotify/build/1.0.18/job/82l87bwbob81dvag

@retep998, any ideas?

**Comment by retep998** [comment]
I'm on it. It appears to be due to appveyor having a newer windows 10 SDK which isn't supported yet.

**Comment by retep998** [comment]
https://github.com/rust-lang/rust/issues/30229

**Comment by passcod** [comment]
@retep998 What's your recommendation, here: apply the temporary fix until the issue is fixed upstream, or wait for upstream?

**Comment by retep998** [comment]
It's up to you. The PR could take several days, especially due to potential bikeshedding on what the proper way to detect the SDK stuff is.

**Comment by jmquigs** [comment]
The vcvars fix seems safe enough, even after upstream is fixed.

**Comment by passcod** [comment]
@jmquigs I saw you made the vcvars change in your branch, could you PR it here? :)
