### ISSUE TITLE
INotifyWatcher::watch returns an error if any subdirectories contain a broken link.

### ISSUE THREAD

**Issue by maurizi** [passcod/rsnotify#47]
This came up on my project: https://github.com/maurizi/retag.rs/issues/23

From what I can tell, because [`follow_links(true)` is called here](https://github.com/passcod/rsnotify/blob/a019f6bfd4511b88c2c14efe7f05679f733b3263/src/inotify/mod.rs#L94-L97), `WalkDir` returns the target path of symlinks, even if they are broken links.  Then when we pass the path over to `inotify`, it correctly returns an error.

@passcod I can think of a couple of ways to fix this.
 - Each item returned by `WalkDir` could be tested to see that it exists before calling `add_watch`
 - Ignore some errors (IO errors like file does not exist) returned by `add_watch` when calling it from `add_watch_recursively`
 - Ignore all errors returned by `add_watch` when calling it from `add_watch_recursively`

What do you think?

**Comment by passcod** [comment]
Ah, I'd have thought the immediate next part in the code (that ignores errors in the lookup) would have solved this. I think the simple thing would just be to completely ignore broken symlinks, at the WalkDir level at least.

I'm idly wondering how this all behaves on other platforms that have symlinks (OS X)... does FSEvent just ignore broken symlinks itself? Hmm.

**Comment by maurizi** [comment]
Maybe the best way to fix this is to remove the call to `follow_symlinks` and then call `WalkDir` again for every symlink found, if it is a valid symlink.

That would also allow `rsnotify` to watch for changes to *the symlink itself*, which would be a nice bonus.

**Comment by maurizi** [comment]
@passcod if you have a preference for how to fix this, I'd be happy to work on a PR.

**Comment by passcod** [comment]
Yep, your last proposition sounds good. If you want to work on it, even more awesome :)

**Comment by maurizi** [comment]
So..... I think I had this all wrong.  The way that `DirEntry::path()` works, it _always_ returns the symlink's path, not it's target (as is noted in the documentation for WalkDir http://burntsushi.net/rustdoc/walkdir/struct.DirEntry.html#method.path).

So actually everything is working?  I think perhaps the original issue reported on my project may have been for a different OS than linux...

Anyways, sorry for the non-bug.

**Comment by passcod** [comment]
No problem, thanks for investigating!
