### ISSUE TITLE
FsEventsWatcher doesn't seem to work on OS X 10.10.5

### ISSUE THREAD

**Issue by joelself** [passcod/rsnotify#50]
I tried the example in the README.md file on current Rust (1.6.0) on my Mac (OS X version 10.10.5) and it doesn't seem to work. I tried using both the RecommendedWatcher and FsEventWatcher to watch /var/log/system.log. I tailed the file at the same time. I could see writes coming in on the tail, but I wasn't receiving any events from my watcher.

Edit: PollWatcher is working.

**Comment by passcod** [comment]
@andelf

**Comment by joelself** [comment]
There's definitely something to do with with the file type, the way it's modified or permissions. I'm trying to tail `/var/log/system.log`. I can read it without elevating to root, but can't write to it without sudo. I tried another FSEvent library: https://github.com/octplane/fsevent-rust and it doesn't get notified when the file is appended, but if I do `sudo touch /var/log/system.log`, it registers that event. I tried rsnotify again, but it doesn't pick up on the the `touch`es so there's still something wrong. 

The file apparently has extended attributes. If I do an `ls -l@` I get:
```shell
-rw-r-----@ 1 root  admin  1164847 Feb  1 16:00 system.log
	com.apple.quarantine	     32 
```

**Comment by octplane** [comment]
I'm away from OS X until next week so I won't be able to dig further but my wild guess is that FSEvent has probably some limitation around extended attributes files. 

Note that rsnotify uses my library internally on OS X so the behavior difference is probably only a configuration detail. The actual issue should probably be sent upstream for further analysis (which would start by looking at stackoverflow opinion on the subject)...

**Comment by joelself** [comment]
I removed the special attribute and it didn't change anything (for either library).

**Comment by joelself** [comment]
I wouldn't take this as very high priority. I only cared about MacOS because I was developing on a Mac. My ultimate targets are Linux and Windows. I'm just going to develop in Linux from now on.

**Comment by octplane** [comment]
After some investigation, It appears this is a (security) limitation of the FSEvent API. I suggest we close that, maybe add a note somewhere in the doc regarding the fact that the PollWatcher might work around this issue.

**Comment by passcod** [comment]
Sounds good. Can you draft something to that effect? I'll add it tonight.

**Comment by passcod** [comment]
Done in #51, may also be able to be covered in #64.

**Comment by umanwizard** [comment]
I believe the analysis in this thread to be wrong. I do not think `/var/log/system.log` is unreadable for security reasons; rather, I think the issue is that FSEvents only delivers file-modified events when a file handle is closed, and whatever daemon writes to that file is not closing it.

See the discussion in https://github.com/notify-rs/notify/issues/240 .
