### ISSUE TITLE
i686-apple-darwin not supported?

### ISSUE THREAD

**Issue by japaric** [passcod/rsnotify#53]
I noticed that i686-apple-darwin it's missing the fsevent{,-sys} dependencies in the [Cargo.toml](https://github.com/passcod/rsnotify/blob/b2c32e1b4efd38e411f9f663c4543c51318a694a/Cargo.toml#L56-L58). Is this target not supported for technical reasons or simply not tested? If the problem is testing I can help to extend the test matrix to cover all the tier-1 unixy platforms like [rust-everywhere does](https://travis-ci.org/japaric/rust-everywhere).

**Comment by passcod** [comment]
It's simply not added to the Cargo.toml. If you want to do aPR for it that'd be great :)

**Comment by passcod** [comment]
Done in #54
