### ISSUE TITLE
std::error::Error implementation for notify::Error

### ISSUE THREAD

**Issue by netvl** [passcod/rsnotify#55]
Consider implementing `std::error::Error` trait for `notify::Error` because it helps with interoperability with other code. Currently I'm unable to use the error with `{}` pattern when formatting a string, for example.

**Comment by julienw** [comment]
> Currently I'm unable to use the error with {} pattern when formatting a string, for example.

This should actually work because Error implements Display. (maybe it didn't when you filed the bug initially though)
