### ISSUE TITLE
Newly created folders are not watched recursively on Ubuntu

### ISSUE THREAD

**Issue by jchlapinski** [passcod/rsnotify#80]
When I run an example code from the doc, rsnotify detects creation of a new subfolder of the watched main folder, however when a file is added to/removed from a newly created subfolder, rsnotify does not generate any events.

I am running this on Ubuntu 16.04 VM inside VMware Workstation. It is ext4 file system.

**Comment by jchlapinski** [comment]
I have found a proper working example in repository, I was not adding new watches for subfolders, sorry for being to hasty.

**Comment by passcod** [comment]
No problem, and this is probably something we will cover in #62.
