### ISSUE TITLE
MacOSX' RecommendedWatcher (FsEventWatcher) doesn't implement Send

### ISSUE THREAD

**Issue by julienw** [passcod/rsnotify#82]
This is misleading because other watchers are Send and so can be moved between threads.

Here is an example of an error I get in MacOS X only:
```
src/lib.rs:643:9: 643:22 error: the trait bound `*mut libc::c_void: std::marker::Send` is not satisfied [E0277]
src/lib.rs:643         thread::spawn(move || {
                                                                                                          ^~~~~~~~~~~~~
src/lib.rs:643:9: 643:22 help: run `rustc --explain E0277` to see a detailed explanation
src/lib.rs:643:9: 643:22 note: `*mut libc::c_void` cannot be sent between threads safely
src/lib.rs:643:9: 643:22 note: required because it appears within the type `notify::FsEventWatcher`
src/lib.rs:643:9: 643:22 note: required because it appears within the type `FsWatcher`
```

**Comment by julienw** [comment]
This is not obvious, but `cf::CFMutableArrayRef` is an alias to `*mut libc::c_void`.

**Comment by julienw** [comment]
I think we could add `unsafe impl Send for FsEventWatcher`, as it seems safe to pass this pointer accross threads. Not sure for Sync, but I think it would be fine as well because the methods that change states use `&mut self`.

What do you think ?

If you agree I can write the patch.

**Comment by passcod** [comment]
Cc @octplane

**Comment by octplane** [comment]
@julienw that would be nice if you could write the patch. Does that only consist in adding the `unsafe..` to the impl ? Would you mind trying to write a test for that too ?

**Comment by julienw** [comment]
Yes, it would be simply adding the `unsafe impl Send//Sync`. I can try to write a test :)

**Comment by octplane** [comment]
Nice 🌅  . Let us know if anything is blocking you.
